### ISSUE TITLE
Incompatible with Ugly Scoreboard Fix and ImmediatelyFast

### ISSUE THREAD

**Issue by andreasdc** [not-coded/NQT#1]
https://modrinth.com/mod/ugly-scoreboard-fix
It creates crash during launch, without it it crashes after joining a server/world, probably incompatible with ImmediatelyFast:
`[03:29:13] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
	at org.spongepowered.asm.mixin.injection.invoke.arg.Args.get(Args.java:70) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.minecraft.class_329.args$cno000$nqt$renderScoreboardSidebar_hook1(class_329.java:9060) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1757(class_329.java:718) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.mixinextras$bridge$13$method_1757(class_329.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.wrapOperation$bmc000$immediatelyfast$batching(class_329.java:1455) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.mixinextras$bridge$20$wrapOperation$bmc000$immediatelyfast$batching(class_329.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.wrapOperation$zlk000$exordium$displayScoreboardSidebarWrapper(class_329.java:6399) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:348) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:926) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]`

**Comment by not-coded** [comment]
seems like this is caused by the title fix mixin
with the ugly scoreboard fix, i dont know anything about

i've released a patch for this, if there are any more incompatible mods then create a pull request editing [this](https://github.com/not-coded/NQT/blob/1.20-1.20.1/src/main/java/net/notcoded/nqt/utils/fixes/titlefix/TitleFix.java)
